#! /bin/bash

sxhkd &
nitrogen --restore &
picom -b &
flameshot &
~/.config/polybar/launch.sh &
dunst -conf ~/.config/dunst/dunstrc &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config normal_border_color  '#141415'
bspc config focused_border_color '#B01F1D'
bspc config top_padding 	10
bspc config bottom_padding 	4
bspc config left_padding 	4
bspc config right_padding 	4

bspc config honor_size_hints	true

bspc config window_gap          10

bspc config split_ratio          	0.55
bspc config borderless_monocle   	true
bspc config gapless_monocle      	false

bspc config ignore_ewmh_focus 		false

bspc rule -a Discord desktop=^3 follow=on
bspc rule -a Brave desktop=^1 
bspc rule -a Code desktop=^2

setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl
#hsetroot -add '#FF7349' -add '#AF3309' -add '#A82126' -add '#631009' -grad>

~
